version: '3.9'
services:
  postgres:
    image: postgres:16-alpine
    environment:
      POSTGRES_USER: app
      POSTGRES_PASSWORD: app
      POSTGRES_DB: ecommerce
    ports: ["5432:5432"]
    volumes:
    - pgdata:/var/lib/postgresql/data
  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: xd@xd.com
      PGADMIN_DEFAULT_PASSWORD: xd
    ports:
      - "5050:80"
  redis:
    image: redis:7-alpine
    ports: ["6379:6379"]
  mailhog:
    image: mailhog/mailhog:latest
    ports: ["8025:8025", "1025:1025"]
volumes:
  pgdata: